version: "3.7"

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"    

services:
  loki:
    image: grafana/loki:2.4.2
    ports:
      - "3100"
    volumes:
      - ./config/loki/loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki
    logging: *loki-logging  

  promtail:
    image: grafana/promtail:2.4.2
    volumes:
      - ./config/loki/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/lib/docker/containers:/host/containers
    command: -config.file /mnt/config/promtail-config.yaml
    networks:
      - loki
    logging: *loki-logging  

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes: 
      - grafana-data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - loki
    environment:
      GF_SECURITY_ADMIN_PASSWORD: testloki
      GF_USERS_DEFAULT_THEME: light
    logging: *loki-logging    

  demo-app:
    image: ealen/echo-server
    ports: 
        - "3001:80"   
    networks:
      - loki
    logging: *loki-logging  

  django-app:
    container_name: django-app
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
        - "8000:8000"
    networks:
      - loki
    logging: *loki-logging
    volumes:
      - ./api:/usr/src/app
      - ./api/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh runserver 0.0.0.0:8000 --traceback -v 3

volumes:
  grafana-data: 

networks:
  loki:

